version: "3"

dotenv:
  - .env.local
  - .env

tasks:
  default:
    desc: Start server with hot-reload
    cmd: gow -s -e go,mod,html run .

  db:
    desc: Create a postgres docker container and run it
    cmds:
      - defer: |
          docker stop htmxtodo_database
          docker rm htmxtodo_database
      - >
        docker run
        -v htmxtodo_data:/var/lib/postgresql/data
        -e POSTGRES_USER=$DB_USER
        -e POSTGRES_PASSWORD=$DB_PASS
        -e POSTGRES_DB=$DB_NAME
        --network host
        --name htmxtodo_database
        postgres:15.3-alpine3.18

  migrate:
    desc: Migrate files inside /migrations folder
    cmd: goose -dir migrations postgres "user=$DB_USER password=$DB_PASS host=$DB_HOST port=$DB_PORT dbname=$DB_NAME sslmode=disable" {{.CLI_ARGS}}

  deploy:
    desc: Deploy project onto a docker container
    cmds:
      - defer: |
          docker stop htmxtodo_server
          docker rm htmxtodo_server
      - >
        docker run
        -e DB_USER=$DB_USER
        -e DB_PASS=$DB_PASS
        -e DB_HOST=$DB_HOST
        -e DB_PORT=$DB_PORT
        -e DB_NAME=$DB_NAME
        --network host
        --name htmxtodo_server
        {{.CLI_ARGS}}
